### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by mbarde** [mbarde/volto-fullcalendar-block#4]
index.js:1 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in CalendarDataProvider (created by FullCalendar)
    in FullCalendar (at View.jsx:62)
    in FullCalendarBlockView (at DefaultView.jsx:46)
    in div (at DefaultView.jsx:39)
    in DefaultView (created by Context.Consumer)
    in injectIntl(DefaultView) (at View.jsx:233)

**Comment by tiberiuichim** [comment]
I haven't actually run the addon (although it looks really good), I think it may be due to the setTimeout() call here:

```
      setTimeout(() => {
        if (!isFullCalendarLoading && calendarRef.current) {
          let events = calendarRef.current.getApi().getEvents();
          setStoredEvents(events);
        }
      });
```

When setting  state in a setTimeout callyou need to check if the component is still mounted. See https://usehooks-typescript.com/react-hook/use-is-mounted
